// Daily Puzzle Data
// Each puzzle is a curated set of movies for a specific day

// Puzzle schedule - maps specific dates to puzzle IDs
// Generated by puzzle-builder
const PUZZLE_SCHEDULE = {
  "2026-01-10": "k7x2m",
  "2026-01-11": "p3n8v",
  "2026-01-12": "amnfm",
  "2026-01-13": "m4k7r",
  "2026-01-14": "qc9xe",
  "2026-01-15": "jgns2",
  "2026-01-16": "r5t1q"
};

const DAILY_PUZZLES = [
  {
    id: "w9j4h",
    theme: "Oscar Best Picture Winners",
    description: "Academy Award winners for Best Picture",
    movieIds: [
      597, 238, 13, 98, 274, 424, 1366, 510, 1422, 6977, 194662, 76203, 376867,
      74643, 399055, 776503, 792, 380, 581, 12162,
    ],
  },
  {
    id: "k7x2m",
    theme: "Manhunter",
    description: "Stylish crime dramas from the master of mood",
    movieIds: [
      949, 1538, 9361, 11322, 82, 8489, 9008, 11454, 11524, 365620, 201088,
      26198,
    ],
  },
  {
    id: "b2f6n",
    theme: "Spielberg, Scorsese & Coppola",
    description: "Movies from three legendary directors",
    movieIds: [
      578, 238, 329, 85, 601, 424, 103, 28, 769, 240, 857, 87, 89, 524, 840,
      1422, 879, 640, 873, 242, 6114, 180, 74, 11324, 106646, 227, 1598, 594,
      217, 57212, 333339, 839, 232, 11352, 7095,
    ],
  },
  {
    id: "r5t1q",
    theme: "Disney Animation Classics",
    description: "Beloved animated films from Disney and Pixar",
    movieIds: [
      8587, 109445, 12, 862, 10020, 812, 10144, 585, 14160, 10681, 38757,
      354912, 10674, 11970, 2062, 150540, 269149, 568124, 37135, 10530, 177572,
      82690, 11544, 11688, 10112, 11886,
    ],
  },
  {
    id: "p3n8v",
    theme: "War of the Worlds",
    description: "",
    movieIds: [
      74, 602, 329865, 2675, 75, 59678, 8337, 755898, 840, 7191, 5491, 137113,
      44943, 9397, 9348, 8974,
    ],
  },
  {
    id: "m4k7r",
    theme: "Natural Born Killers",
    description: "",
    movieIds: [
      274, 1949, 539, 1359, 504, 807, 320, 10279, 241, 71859, 12149, 768, 9740,
    ],
  },
  {
    id: "9nw35",
    theme: "test",
    description: "",
    movieIds: [
      2105, // American Pie (1999)
      37135, // Tarzan (1999)
      872585, // Oppenheimer (2023)
      2034,
      9778,
      374720, // Dunkirk (2017)
      27205, // Inception (2010)
      346698, // Barbie (2023),
      83533,
    ],
  },
  {
    id: "amnfm",
    theme: "Funny People",
    description: "",
    movieIds: [
      20829, // Funny People (Jul 31, 2009)
      10322, // Being There (Dec 19, 1979)
      489, // Good Will Hunting (Jan 9, 1998)
      38, // Eternal Sunshine of the Spotless Mind (Mar 19, 2004)
      873, // The Color Purple (Jan 16, 1987)
      153, // Lost in Translation (Sep 18, 2003)
      86555, // Take This Waltz (May 25, 2012)
      22318, // Permanent Midnight (Sep 16, 1998)
      1125, // Dreamgirls (Dec 25, 2006)
      87492, // Foxcatcher (Jan 16, 2015)
      17450, // Pennies from Heaven (Jan 1, 1982)
      25793, // Precious (Nov 20, 2009)
      64690, // Drive (Sep 16, 2011)
      1262, // Stranger Than Fiction (Nov 10, 2006)
      403, // Driving Miss Daisy (Jan 26, 1990)
      8051, // Punch-Drunk Love (Oct 25, 2002)
    ],
  },
  {
    id: "qc9xe",
    theme: "Ready Player One",
    description: "",
    movieIds: [
      333339, // Ready Player One (Mar 29, 2018)
      257344, // Pixels (Jul 24, 2015)
      980489, // Gran Turismo (Aug 25, 2023)
      97, // Tron (Jul 9, 1982)
      183, // The Wizard (Dec 15, 1989)
      22538, // Scott Pilgrim vs. the World (Aug 13, 2010)
      1946, // eXistenZ (Apr 19, 1999)
      82690, // Wreck-It Ralph (Nov 2, 2012)
      550988, // Free Guy (Aug 13, 2021)
      860, // WarGames (Jun 3, 1983)
      9900, // Grandma's Boy (Jan 6, 2006)
      325348, // Hardcore Henry (Apr 8, 2016)
      11884, // The Last Starfighter (Jul 13, 1984)
      18501, // Gamer (Sep 4, 2009)
    ],
  },
    {
    id: "jgns2",
    theme: "Speed",
    description: "",
    movieIds: [
      1637, // Speed (Jun 9, 1994)
      2119, // Days of Thunder (Jun 27, 1990)
      7459, // Speed Racer (May 9, 2008)
      9659, // Mad Max (May 2, 1980)
      13282, // Death Race 2000 (Apr 30, 1975)
      11286, // The Cannonball Run (Jun 19, 1981)
      911430, // F1 (Jun 27, 2025)
      5920, // Le Mans (Jun 23, 1971)
      916, // Bullitt (Oct 17, 1968)
      525, // The Blues Brothers (Jun 16, 1980)
      64690, // Drive (Sep 16, 2011)
    ],
  },
  // Future puzzles will be added here
];

// Get date string in Eastern Time (America/New_York)
function getEasternDateString(date) {
  return date.toLocaleDateString("en-CA", { timeZone: "America/New_York" });
}

// Get a puzzle by its ID
function getPuzzleById(id) {
  return DAILY_PUZZLES.find((p) => p.id === id) || null;
}

// Get the puzzle for a specific date
function getPuzzleForDate(date) {
  // Convert to Eastern Time date string for consistent comparison
  const targetDateStr = getEasternDateString(date);
  const targetDate = new Date(targetDateStr + "T00:00:00");

  // Check if there's a scheduled puzzle for this date
  const dateStr = targetDate.toISOString().split("T")[0];
  if (PUZZLE_SCHEDULE[dateStr]) {
    const scheduled = DAILY_PUZZLES.find(
      (p) => p.id === PUZZLE_SCHEDULE[dateStr]
    );
    if (scheduled) return scheduled;
  }

  // Fall back to rotation based on first scheduled date
  const scheduledDates = Object.keys(PUZZLE_SCHEDULE).sort();
  if (scheduledDates.length === 0) {
    return DAILY_PUZZLES[0] || null;
  }

  const firstDateStr = scheduledDates[0];
  const firstDate = new Date(firstDateStr + "T00:00:00");

  // If before first puzzle, return null
  if (targetDate < firstDate) {
    return null;
  }

  // Calculate which puzzle to show (cycles through available puzzles)
  const daysSinceFirst = Math.floor(
    (targetDate - firstDate) / (1000 * 60 * 60 * 24)
  );
  const puzzleIndex = daysSinceFirst % DAILY_PUZZLES.length;

  return DAILY_PUZZLES[puzzleIndex];
}

// Get today's puzzle (based on Eastern Time)
function getTodaysPuzzle() {
  return getPuzzleForDate(new Date());
}

// Get puzzle number for a date (1-indexed, uses Eastern Time)
function getPuzzleNumber(date) {
  // Convert to Eastern Time date string for consistent comparison
  const targetDateStr = getEasternDateString(date);
  const targetDate = new Date(targetDateStr + "T00:00:00");

  // Use first scheduled date as the start
  const scheduledDates = Object.keys(PUZZLE_SCHEDULE).sort();
  if (scheduledDates.length === 0) {
    return null;
  }

  const firstDateStr = scheduledDates[0];
  const firstDate = new Date(firstDateStr + "T00:00:00");

  if (targetDate < firstDate) {
    return null;
  }

  const daysSinceFirst = Math.floor(
    (targetDate - firstDate) / (1000 * 60 * 60 * 24)
  );
  return daysSinceFirst + 1;
}

// Get all past puzzles (including today) for the archive
function getArchivePuzzles() {
  // Use Eastern Time for determining "today"
  const todayStr = getEasternDateString(new Date());
  const today = new Date(todayStr + "T00:00:00");

  // Find the earliest date from PUZZLE_SCHEDULE
  const scheduledDates = Object.keys(PUZZLE_SCHEDULE).sort();
  if (scheduledDates.length === 0) {
    return [];
  }

  const firstDateStr = scheduledDates[0];
  const firstDate = new Date(firstDateStr + "T00:00:00");

  // If today is before first puzzle, no archive yet
  if (today < firstDate) {
    return [];
  }

  const archive = [];
  const currentDate = new Date(firstDate);
  let puzzleNum = 1;

  while (currentDate <= today) {
    const dateStr = currentDate.toISOString().split("T")[0];
    const puzzle = getPuzzleForDate(currentDate);

    if (puzzle) {
      archive.push({
        puzzleNumber: puzzleNum,
        date: dateStr,
        puzzle: puzzle,
        isToday: dateStr === todayStr,
      });
    }

    currentDate.setDate(currentDate.getDate() + 1);
    puzzleNum++;
  }

  // Return in reverse chronological order (newest first)
  return archive.reverse();
}
