// Daily Puzzle Data
// Each puzzle is a curated set of movies for a specific day

// Puzzle schedule - maps specific dates to puzzle IDs
// Generated by puzzle-builder
const PUZZLE_SCHEDULE = {
  "2026-01-10": "k7x2m",
  "2026-01-11": "p3n8v",
  "2026-01-12": "amnfm",
  "2026-01-13": "m4k7r",
  "2026-01-14": "qc9xe",
  "2026-01-15": "jgns2",
  "2026-01-16": "dhk7k",
  "2026-01-17": "g2h5y",
  "2026-01-18": "r5t1q",
  "2026-01-19": "e2zzy",
  "2026-01-20": "k2jq9",
  "2026-01-21": "62wgc",
  "2026-01-22": "r829v",
  "2026-01-23": "qje3j",
  "2026-01-25": "ah7yk",
  "2026-01-26": "rvtak",
  "2026-01-27": "vrrqg",
  "2026-01-28": "pcpxv"
};

const DAILY_PUZZLES = [
  {
    id: "w9j4h",
    theme: "Oscar Best Picture Winners",
    description: "Academy Award winners for Best Picture",
    movieIds: [
      597, 238, 13, 98, 274, 424, 1366, 510, 1422, 6977, 194662, 76203, 376867,
      74643, 399055, 776503, 792, 380, 581, 12162,
    ],
  },
  {
    id: "k7x2m",
    theme: "Manhunter",
    description: "Stylish crime dramas from the master of mood",
    emoji: "🔍",
    movieIds: [
      949, 1538, 9361, 11322, 82, 8489, 9008, 11454, 11524, 365620, 201088,
      26198,
    ],
  },
  {
    id: "b2f6n",
    theme: "Spielberg, Scorsese & Coppola",
    description: "Movies from three legendary directors",
    movieIds: [
      578, 238, 329, 85, 601, 424, 103, 28, 769, 240, 857, 87, 89, 524, 840,
      1422, 879, 640, 873, 242, 6114, 180, 74, 11324, 106646, 227, 1598, 594,
      217, 57212, 333339, 839, 232, 11352, 7095,
    ],
  },
  {
    id: "r5t1q",
    theme: "Disney Animation Classics",
    description: "Beloved animated films from Disney and Pixar",
    emoji: "🏰",
    movieIds: [
      8587, 109445, 12, 862, 10020, 812, 10144, 585, 14160, 10681, 38757,
      354912, 10674, 11970, 2062, 150540, 269149, 568124, 37135, 10530, 177572,
      82690, 11544, 11688, 10112, 11886,
    ],
  },
  {
    id: "p3n8v",
    theme: "War of the Worlds",
    description: "",
    movieIds: [
      74, 602, 329865, 2675, 75, 59678, 8337, 755898, 840, 7191, 5491, 137113,
      44943, 9397, 9348, 8974,
    ],
  },
  {
    id: "m4k7r",
    theme: "Natural Born Killers",
    description: "",
    movieIds: [
      274, 1949, 539, 1359, 504, 807, 320, 10279, 241, 71859, 12149, 768, 9740,
    ],
  },
  {
    id: "9nw35",
    theme: "test",
    description: "",
    movieIds: [
      2105, // American Pie (1999)
      37135, // Tarzan (1999)
      872585, // Oppenheimer (2023)
      2034,
      9778,
      374720, // Dunkirk (2017)
      27205, // Inception (2010)
      346698, // Barbie (2023),
      83533,
    ],
  },
  {
    id: "amnfm",
    theme: "Funny People",
    description: "",
    movieIds: [
      20829, // Funny People (Jul 31, 2009)
      10322, // Being There (Dec 19, 1979)
      489, // Good Will Hunting (Jan 9, 1998)
      38, // Eternal Sunshine of the Spotless Mind (Mar 19, 2004)
      873, // The Color Purple (Jan 16, 1987)
      153, // Lost in Translation (Sep 18, 2003)
      86555, // Take This Waltz (May 25, 2012)
      22318, // Permanent Midnight (Sep 16, 1998)
      1125, // Dreamgirls (Dec 25, 2006)
      87492, // Foxcatcher (Jan 16, 2015)
      17450, // Pennies from Heaven (Jan 1, 1982)
      25793, // Precious (Nov 20, 2009)
      64690, // Drive (Sep 16, 2011)
      1262, // Stranger Than Fiction (Nov 10, 2006)
      403, // Driving Miss Daisy (Jan 26, 1990)
      8051, // Punch-Drunk Love (Oct 25, 2002)
    ],
  },
  {
    id: "qc9xe",
    theme: "Ready Player One",
    description: "",
    movieIds: [
      333339, // Ready Player One (Mar 29, 2018)
      257344, // Pixels (Jul 24, 2015)
      980489, // Gran Turismo (Aug 25, 2023)
      97, // Tron (Jul 9, 1982)
      183, // The Wizard (Dec 15, 1989)
      22538, // Scott Pilgrim vs. the World (Aug 13, 2010)
      1946, // eXistenZ (Apr 19, 1999)
      82690, // Wreck-It Ralph (Nov 2, 2012)
      550988, // Free Guy (Aug 13, 2021)
      860, // WarGames (Jun 3, 1983)
      9900, // Grandma's Boy (Jan 6, 2006)
      325348, // Hardcore Henry (Apr 8, 2016)
      11884, // The Last Starfighter (Jul 13, 1984)
      18501, // Gamer (Sep 4, 2009)
    ],
  },
    {
    id: "jgns2",
    theme: "Speed",
    description: "",
    movieIds: [
      1637, // Speed (Jun 9, 1994)
      2119, // Days of Thunder (Jun 27, 1990)
      7459, // Speed Racer (May 9, 2008)
      9659, // Mad Max (May 2, 1980)
      13282, // Death Race 2000 (Apr 30, 1975)
      11286, // The Cannonball Run (Jun 19, 1981)
      911430, // F1 (Jun 27, 2025)
      5920, // Le Mans (Jun 23, 1971)
      916, // Bullitt (Oct 17, 1968)
      525, // The Blues Brothers (Jun 16, 1980)
      64690, // Drive (Sep 16, 2011)
    ],
  },
    {
    id: "dhk7k",
    theme: "Cats & Dogs",
    description: "",
    movieIds: [
      10992, // Cats & Dogs (Jul 4, 2001)
      9598, // Babe (Aug 4, 1995)
      448119, // Dolittle (Jan 17, 2020)
      9986, // Charlotte's Web (Dec 15, 2006)
      10137, // Stuart Little (Dec 17, 1999)
      912908, // Strays (Aug 18, 2023)
      411, // The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (Dec 9, 2005)
      454626, // Sonic the Hedgehog (Feb 14, 2020)
      6878, // Homeward Bound: The Incredible Journey (Feb 12, 1993)
      20723, // That Darn Cat! (Dec 2, 1965)
      47951, // The Adventures of Milo and Otis (Aug 25, 1989)
      165013, // A Talking Cat!?! (Feb 18, 2013)
    ],
  },
    {
    id: "g2h5y",
    theme: "Minnesota",
    description: "",
    movieIds: [
      275, // Fargo (Apr 5, 1996)
      10223, // A Simple Plan (Jan 22, 1999)
      11520, // Grumpy Old Men (Dec 25, 1993)
      9279, // Jingle All the Way (Nov 22, 1996)
      31504, // Little Big League (Jun 29, 1994)
      10475, // Factotum (Aug 18, 2006)
      10414, // The Mighty Ducks (Oct 2, 1992)
      9701, // North Country (Sep 12, 2005)
      1183392, // Airport (Jan 1, 1981)
      14536, // New in Town (Jan 30, 2009)
      19994, // Jennifer's Body (Sep 18, 2009)
    ],
  },
      {
    id: "ah7yk",
    theme: "Any Given Sunday",
    description: "",
    emoji: "🏈",
    movieIds: [
      9563, // Any Given Sunday (Dec 22, 1999)
      13416, // Friday Night Lights (Oct 8, 2004)
      18047, // Brian's Song (Nov 30, 1971)
      10637, // Remember the Titans (Sep 29, 2000)
      22881, // The Blind Side (Nov 20, 2009)
      14534, // Rudy (Oct 13, 1993)
      4985, // The Longest Yard (Aug 21, 1974)
      11170, // We Are Marshall (Dec 12, 2006)
      10393, // The Replacements (Aug 11, 2000)
      14709, // Varsity Blues (Jan 15, 1999)
      4942, // Leatherheads (Mar 24, 2008)
      10663, // The Waterboy (Nov 6, 1998)
      20726, // Little Giants (Oct 14, 1994)
    ],
  },
    {
    id: "qje3j",
    theme: "The Perfect Storm",
    description: "",
    movieIds: [
      2133, // The Perfect Storm (Jun 30, 2000)
      664, // Twister (May 10, 1996)
      435, // The Day After Tomorrow (May 28, 2004)
      254128, // San Andreas (May 29, 2015)
      9619, // Dante's Peak (Feb 7, 1997)
      10357, // Volcano (Apr 25, 1997)
      503, // Poseidon (May 12, 2006)
      14161, // 2012 (Nov 13, 2009)
      80278, // The Impossible (Jan 4, 2013)
      11123, // Earthquake (Nov 15, 1974)
      551, // The Poseidon Adventure (Dec 13, 1972)
      524047, // Greenland (Dec 18, 2020)
      95, // Armageddon (Jul 1, 1998)
      8656, // Deep Impact (May 8, 1998)
      76649, // Pompeii (Feb 21, 2014)
      406759, // Moonfall (Feb 4, 2022)
      9341, // The Core (Mar 28, 2003)
      166680, // Avalanche (Sep 29, 1978)
      395991, // Only the Brave (Oct 20, 2017)
      86834, // Noah (Mar 28, 2014)
      205321, // Sharknado (Jul 11, 2013)
    ],
  },
      {
    id: "vrrqg",
    theme: "The American President",
    description: "",
    emoji: "🇺🇸",
    movieIds: [
      9087, // The American President (Nov 17, 1995)
      72976, // Lincoln (Nov 16, 2012)
      87504, // Hyde Park on Hudson (Dec 7, 2012)
      820, // JFK (Dec 20, 1991)
      353575, // LBJ (Nov 3, 2017)
      10858, // Nixon (Dec 22, 1995)
      10523, // W. (Oct 17, 2008)
      11566, // Dave (May 7, 1993)
      9772, // Air Force One (Jul 25, 1997)
      17795, // My Fellow Americans (Dec 20, 1996)
      11499, // Frost/Nixon (Dec 5, 2008)
      16406, // Dick (Aug 4, 1999)
      301348, // Elvis & Nixon (Apr 22, 2016)
      9776, // Head of State (Mar 28, 2003)
      11973, // Thirteen Days (Dec 25, 2000)
      117251, // White House Down (Jun 28, 2013)
      117263, // Olympus Has Fallen (Mar 22, 2013)
      9440, // Primary Colors (Mar 20, 1998)
      72331, // Abraham Lincoln: Vampire Hunter (Jun 22, 2012)
    ],
  },
      {
    id: "rvtak",
    theme: "The Wrestler",
    description: "",
    emoji: "🤼",
    movieIds: [
      12163, // The Wrestler (Oct 12, 2008)
      19371, // Mr. Nanny (Oct 8, 1993)
      277834, // Moana (Nov 23, 2016)
      106, // Predator (Jun 12, 1987)
      8337, // They Live (Nov 4, 1988)
      2493, // The Princess Bride (Oct 9, 1987)
      557, // Spider-Man (May 3, 2002)
      118340, // Guardians of the Galaxy (Aug 1, 2014)
      463257, // The Peanut Butter Falcon (Aug 23, 2019)
      1850, // Man on the Moon (Dec 22, 1999)
      37931, // MacGruber (May 21, 2010)
      14636, // The Condemned (Apr 27, 2007)
      10007, // See No Evil (May 19, 2006)
      44946, // Knucklehead (Oct 22, 2010)
    ],
  },
      {
    id: "pcpxv",
    theme: "The Nic Cage Challenge",
    description: "",
    emoji: "🎭",
    movieIds: [
      2757, // Adaptation. (Dec 6, 2002)
      9679, // Gone in Sixty Seconds (Jun 9, 2000)
      11699, // Bad Lieutenant: Port of Call - New Orleans (Dec 11, 2009)
      451, // Leaving Las Vegas (Oct 27, 1995)
      2059, // National Treasure (Nov 19, 2004)
      1830, // Lord of War (Sep 16, 2005)
      324857, // Spider-Man: Into the Spider-Verse (Dec 14, 2018)
      1701, // Con Air (Jun 6, 1997)
      754, // Face/Off (Jun 27, 1997)
      1250, // Ghost Rider (Feb 16, 2007)
      9708, // The Wicker Man (Sep 1, 2006)
      2039, // Moonstruck (Jan 15, 1988)
      9802, // The Rock (Jun 7, 1996)
      483, // Wild at Heart (Aug 17, 1990)
      5994, // The Family Man (Dec 12, 2000)
      378, // Raising Arizona (Apr 17, 1987)
      6637, // National Treasure: Book of Secrets (Dec 21, 2007)
      23483, // Kick-Ass (Apr 16, 2010)
      635731, // Pig (Jul 16, 2021)
      460885, // Mandy (Sep 13, 2018)
      8688, // Snake Eyes (Aug 7, 1998)
      10013, // Peggy Sue Got Married (Oct 10, 1986)
      8224, // 8MM (Feb 26, 1999)
      8649, // Bringing Out the Dead (Oct 22, 1999)
      7270, // Matchstick Men (Sep 12, 2003)
      157847, // Joe (Apr 11, 2014)
      1738, // Next (Apr 26, 2007)
      1852, // World Trade Center (Aug 9, 2006)
      6963, // The Weather Man (Oct 20, 2005)
      648579, // The Unbearable Weight of Massive Talent (Apr 22, 2022)
    ],
  },
  // Future puzzles will be added here
];

// Get date string in Eastern Time (America/New_York)
function getEasternDateString(date) {
  return date.toLocaleDateString("en-CA", { timeZone: "America/New_York" });
}

// Get a puzzle by its ID
function getPuzzleById(id) {
  return DAILY_PUZZLES.find((p) => p.id === id) || null;
}

// Get the puzzle for a specific date
function getPuzzleForDate(date) {
  // Convert to Eastern Time date string for consistent comparison
  const targetDateStr = getEasternDateString(date);
  const targetDate = new Date(targetDateStr + "T00:00:00");

  // Check if there's a scheduled puzzle for this date
  const dateStr = targetDate.toISOString().split("T")[0];
  if (PUZZLE_SCHEDULE[dateStr]) {
    const scheduled = DAILY_PUZZLES.find(
      (p) => p.id === PUZZLE_SCHEDULE[dateStr]
    );
    if (scheduled) return scheduled;
  }

  // Fall back to filling empty days with unused puzzles
  const scheduledDates = Object.keys(PUZZLE_SCHEDULE).sort();
  if (scheduledDates.length === 0) {
    return DAILY_PUZZLES[0] || null;
  }

  const firstDateStr = scheduledDates[0];
  const firstDate = new Date(firstDateStr + "T00:00:00");

  // If before first puzzle, return null
  if (targetDate < firstDate) {
    return null;
  }

  // Build set of puzzles already used (scheduled for dates <= target date)
  const usedPuzzleIds = new Set();
  for (const [schedDate, puzzleId] of Object.entries(PUZZLE_SCHEDULE)) {
    if (new Date(schedDate + "T00:00:00") <= targetDate) {
      usedPuzzleIds.add(puzzleId);
    }
  }

  // Get puzzles scheduled for future dates (can't use these yet)
  const futureScheduledIds = new Set(
    Object.entries(PUZZLE_SCHEDULE)
      .filter(([schedDate]) => new Date(schedDate + "T00:00:00") > targetDate)
      .map(([, puzzleId]) => puzzleId)
  );

  // Walk through each day from first date to target date to track what gets used on empty days
  const currentDate = new Date(firstDate);
  while (currentDate < targetDate) {
    const currentDateStr = currentDate.toISOString().split("T")[0];
    if (!PUZZLE_SCHEDULE[currentDateStr]) {
      // This was an empty day - find what puzzle it would use
      const availableForThatDay = DAILY_PUZZLES.filter(
        p => !usedPuzzleIds.has(p.id) && !futureScheduledIds.has(p.id)
      );
      if (availableForThatDay.length > 0) {
        usedPuzzleIds.add(availableForThatDay[0].id);
      }
    }
    currentDate.setDate(currentDate.getDate() + 1);
  }

  // Now find an unused puzzle for this date (excluding future-scheduled puzzles)
  const availablePuzzles = DAILY_PUZZLES.filter(
    p => !usedPuzzleIds.has(p.id) && !futureScheduledIds.has(p.id)
  );

  if (availablePuzzles.length === 0) {
    return null; // No more unique puzzles available
  }

  return availablePuzzles[0];
}

// Get today's puzzle (based on Eastern Time)
function getTodaysPuzzle() {
  return getPuzzleForDate(new Date());
}

// Get puzzle number for a date (1-indexed, uses Eastern Time)
function getPuzzleNumber(date) {
  // Convert to Eastern Time date string for consistent comparison
  const targetDateStr = getEasternDateString(date);
  const targetDate = new Date(targetDateStr + "T00:00:00");

  // Use first scheduled date as the start
  const scheduledDates = Object.keys(PUZZLE_SCHEDULE).sort();
  if (scheduledDates.length === 0) {
    return null;
  }

  const firstDateStr = scheduledDates[0];
  const firstDate = new Date(firstDateStr + "T00:00:00");

  if (targetDate < firstDate) {
    return null;
  }

  const daysSinceFirst = Math.floor(
    (targetDate - firstDate) / (1000 * 60 * 60 * 24)
  );
  return daysSinceFirst + 1;
}

// Get all past puzzles (including today) for the archive
function getArchivePuzzles() {
  // Use Eastern Time for determining "today"
  const todayStr = getEasternDateString(new Date());
  const today = new Date(todayStr + "T00:00:00");

  // Find the earliest date from PUZZLE_SCHEDULE
  const scheduledDates = Object.keys(PUZZLE_SCHEDULE).sort();
  if (scheduledDates.length === 0) {
    return [];
  }

  const firstDateStr = scheduledDates[0];
  const firstDate = new Date(firstDateStr + "T00:00:00");

  // If today is before first puzzle, no archive yet
  if (today < firstDate) {
    return [];
  }

  const archive = [];
  const currentDate = new Date(firstDate);
  let puzzleNum = 1;

  while (currentDate <= today) {
    const dateStr = currentDate.toISOString().split("T")[0];
    const puzzle = getPuzzleForDate(currentDate);

    if (puzzle) {
      archive.push({
        puzzleNumber: puzzleNum,
        date: dateStr,
        puzzle: puzzle,
        isToday: dateStr === todayStr,
      });
    }

    currentDate.setDate(currentDate.getDate() + 1);
    puzzleNum++;
  }

  // Return in reverse chronological order (newest first)
  return archive.reverse();
}
